version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: front-market-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: frontmarket
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - front-market-network

  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front-market-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/frontmarket?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 7d
      CLIENT_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - front-market-network
    volumes:
      - ./uploads:/app/uploads

  # Frontend (for development)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: front-market-client
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - front-market-network
    volumes:
      - ./client:/app
      - /app/node_modules

  # Redis for session storage (optional)
  redis:
    image: redis:7-alpine
    container_name: front-market-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - front-market-network
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:

networks:
  front-market-network:
    driver: bridge
